[package]
name = "rust-toy-webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["rt"] }
log = "0.4.22"
env_logger = "0.11.5"
